config/routes.rb
Clippr::Application.routes.draw do
  resources :authors do
    resources :books do
      member do
        get 'html_export'
      end
      resources :clippings do
        member do
          get 'html_export'
        end
        resource :instapaper_reference
      end
    end
  end
  resources :imports
  resources :clippings

  resource :export do
    member do
      get "download"
      post "update_html_settings"
    end
  end
  
  root :to => "books#index"
  
  

end

app/models/clipping.rb
class Clipping < ActiveRecord::Base
  belongs_to :import
  belongs_to :book
  has_one :note, :class_name => "Note", :foreign_key => "related_clipping_id"
  has_one :instapaper_reference

  def author
    book.author
  end

  def loc
    start_location
  end

  def self.create_from_chunk_for_import(chunk, import)
    author_obj = Author.find_or_create_by_name(chunk.author)
    book_obj = Book.find_or_create_by_title_and_author_id(chunk.title, author_obj.id)
    self.create(:content => chunk.content,
                :clipped_at => chunk.clipped_at,
                :start_location => chunk.start_loc,
                :end_location => chunk.end_loc,
                :page => chunk.page,
                :author_id => author_obj.id,
                :book_id => book_obj.id,
                :import_id => import.id)
  end
  
  def self.find_related_clipping(location)
    Clipping.first(:conditions => ["start_location <= ? AND end_location >= ?", location, location])
  end
  
  def location_string
    if single_location?
      "#{start_location}"
    else
      "#{start_location}-#{end_location}"
    end
  end
  
  def single_location?
    start_location == end_location
  end

  def zero_location?
    # ie it's come from a PDF, which has no locations.
    start_location == 0 && end_location == 0
  end

  def is_pdf?
    zero_location?
  end

  def instapaper?
    #this should probably be based on hardwired ID, not a string.
    author.name == "Instapaper"
  end
  
  def to_xml(options={})
    super({:except => ['import_id', 'id', 'author_id','book_id', 'created_at','updated_at', 'title'],
          :include => {:instapaper_reference => {}, :note => {}, :book => {:include => :author}}}.merge(options))
  end

  def to_json(options={})
    super
  end

  def to_templated_html(template)
    output = template.gsub("$quote", self.content)
    output = output.gsub("$locations", "Locations: " + self.location_string)
    if self.note
      output = output.gsub("$ifnote", "").gsub("$endifnote", "")
      output = output.gsub("$note", self.note.content)
    else
      output = output.gsub(/(\$ifnote).+(\$endifnote)/, "")
    end
  end
end

app/controllers/clippings_controller.rb
class ClippingsController < ApplicationController
  before_filter :scope_to_clipping, :except => [:index]

  def index
    @clippings = Clipping.page(params[:page])
  end

  def html_export
    render :text => @clipping.to_templated_html(Settings.single_clipping_html_template)
  end
  
  private

  def scope_to_clipping
    @clipping = Clipping.find(params[:id])
  end
end

app/helpers/clippings_helper.rb
module ClippingsHelper
end

app/views/clippings/_clipping.html.haml
%li
  %h3
    .datetime
      On
      = format_datetime(clipping.clipped_at)
    .location-metadata
      - if clipping.zero_location?
        %span.is_pdf PDF
      - else
        - if clipping.single_location?
          Location:
        - else
          Locations:
        = clipping.location_string
        - if local_assigns[:show_book]
          - if clipping.instapaper? && clipping.instapaper_reference
            (#{link_to clipping.instapaper_reference.title, clipping.instapaper_reference.url} via #{link_to "Instapaper", [clipping.book.author, clipping.book]})
          - else
            (#{link_to clipping.book.display_name, [clipping.book.author, clipping.book]} by #{link_to clipping.book.author.name, clipping.book.author})
    .export
      = link_to "Export as HTML", html_export_author_book_clipping_path(clipping.book.author, clipping.book, clipping), :class => "clipping_html_export"
    =cleardiv
  %blockquote= clipping.content
  - if clipping.note
    .note= clipping.note.content
  - if clipping.instapaper?
    = render :partial => "clippings/instapaper_reference", :locals => {:clipping => clipping}

app/views/clippings/_instapaper_reference.html.haml
.instapaper
  - if clipping.instapaper_reference
    %p.show_reference
      %b From:
      = link_to clipping.instapaper_reference.title, clipping.instapaper_reference.url
      = link_to "(edit)", new_author_book_clipping_instapaper_reference_path(clipping.book.author, clipping.book, clipping), :class => "toggle_instapaper_form"
  - else
    %p.find_reference
      = link_to "Find reference", new_author_book_clipping_instapaper_reference_path(clipping.book.author, clipping.book,clipping), :class => "find_instapaper_reference"
      = image_tag("spinner.gif", :class=>"instapaper_spinner")
  .instapaper_form
    = form_for clipping.instapaper_reference || InstapaperReference.new, :url => author_book_clipping_instapaper_reference_path(clipping.book.author, clipping.book, clipping) do |f|
      %p
        = label_tag :url, "URL: "
        = text_field :instapaper_reference, :url, :id => "url_field_#{clipping.id}"
        = label_tag :title, "Title: "
        = text_field :instapaper_reference, :title, :id => "title_field_#{clipping.id}"
        = submit_tag "Save", :class => "instapaper_submit btn"
        = link_to "Cancel", "#", :class => "cancel_instapaper_ref_form"
        = link_to "Delete", author_book_clipping_instapaper_reference_path(clipping.book.author, clipping.book, clipping), :method => :delete, :class => "delete_reference"
        = image_tag("spinner.gif", :class=>"form_spinner")

app/views/clippings/index.html.haml
- content_for :title_element do
  Clippings : 

-content_for :title do
  Clippings


%ul.clippings
  = render :partial => "clippings/clipping", :collection => @clippings, :locals => {:show_book => true}

= paginate @clippings