config/routes.rb
Clippr::Application.routes.draw do
  resources :authors do
    resources :books do
      member do
        get 'html_export'
      end
      resources :clippings do
        member do
          get 'html_export'
        end
        resource :instapaper_reference
      end
    end
  end
  resources :imports
  resources :clippings

  resource :export do
    member do
      get "download"
      post "update_html_settings"
    end
  end
  
  root :to => "books#index"
  
  

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  has_many :clippings, :dependent => :destroy
  has_many :notes, :dependent => :destroy

  acts_as_url :display_name, :url_attribute => :slug, :sync_url => true

  after_create :populate_display_name

  def to_param
    slug
  end

  def title_and_author_for_html(template)
    template.gsub("$title", self.display_name).gsub("$author", self.author.name)
  end

  private

  def populate_display_name
    self.display_name = self.title
    self.save
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :scope_to_book, :only => [:show, :edit, :update, :html_export]
  
  def index
    @books = Book.all
  end
  
  def show
    respond_to do |format|
      format.html
      format.xml do 
        render :xml => @book.clippings.to_xml
      end
    end
  end

  def html_export
    output = ""
    output << @book.title_and_author_for_html(Settings.book_title_html_template)
    @book.clippings.each do |clipping|
      output << clipping.to_templated_html(Settings.single_clipping_html_template)
    end
    render :text => output
  end

  def update
    @book.display_name = params[:book][:display_name]
    @book.save
    redirect_to [@book.author, @book]
  end
  
  private
  
  def scope_to_book
    @book = Book.where(:slug => params[:id]).includes([:clippings, :notes]).first
  end
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.haml
%li{:class => cycle("odd", "even")}
  .row
    .details.span8
      %h3= link_to book.display_name, [book.author, book]
      %h4= book.author.name
    .clippings-count.span4
      %span= book.clippings.size
      = book.clippings.size == 1 ? "clipping" : "clippings"
    .notes-count.span4
      %span=book.notes.size
      = book.notes.size == 1 ? "note" : "notes"

app/views/books/edit.html.haml
- content_for :title_element do
  Edit "#{@book.display_name}" : #{@book.author.name} :

- content_for :title do
  Edit "#{@book.display_name}" (#{link_to @book.author.name, @book.author})

- form_for [@book.author, @book] do |f|
  .clearfix 
    = f.label "Title to display"
    .input
      = f.text_field :display_name, :class => "xlarge"
  .actions
    = f.submit "Update", :class => "btn primary"

app/views/books/index.html.haml
- content_for :title_element do
  Books : 

- content_for :title do
  Books

%ul.books
  - for book in @books
    - if book.clippings.any? || book.notes.any?
      = render :partial => "books/book", :locals => {:book => book}

app/views/books/show.html.haml
- content_for :title_element do
  #{@book.display_name} : #{@book.author.name} :

- content_for :title do
  = @book.display_name
  (#{link_to @book.author.name, @book.author})
%p= link_to "Edit book title", edit_author_book_path(@book.author, @book)
%p
  - if @book.clippings.size > 1
    #{@book.clippings.size} clippings, between #{format_datetime(@book.clippings.first.clipped_at)} and #{format_datetime(@book.clippings.last.clipped_at)}.
  - elsif @book.clippings.size == 1
    1 clipping, on #{format_datetime(@book.clippings.first.clipped_at)}.

  = link_to "Export clippings as XML.", author_book_path(@book.author, @book, :format => :xml)
  = link_to "Export book as HTML for blog.", html_export_author_book_path(@book.author, @book), :class => "book_html_export"

%ul.clippings
  = render :partial => "clippings/clipping", :collection => @book.clippings