config/routes.rb
Clippr::Application.routes.draw do
  resources :authors do
    resources :books do
      member do
        get 'html_export'
      end
      resources :clippings do
        member do
          get 'html_export'
        end
        resource :instapaper_reference
      end
    end
  end
  resources :imports
  resources :clippings

  resource :export do
    member do
      get "download"
      post "update_html_settings"
    end
  end
  
  root :to => "books#index"
  
  

end

app/controllers/exports_controller.rb
class ExportsController < ApplicationController
  def show
    @html_template = Settings.single_clipping_html_template
    @title_template = Settings.book_title_html_template
  end

  def download 
    if params[:start_date] && params[:end_date]
      # TODO: there has to be a more native way of interpreting those bloody
      # date selects
      start_date = [params[:start_date]["(1i)"], params[:start_date]["(2i)"], params[:start_date]["(3i)"]].join("-")
      end_date = [params[:end_date]["(1i)"], params[:end_date]["(2i)"], params[:end_date]["(3i)"]].join("-")
      start_datetime = DateTime.parse(start_date)
      end_datetime = DateTime.parse(end_date)
      @clippings = Clipping.where("clipped_at >= ?", start_datetime).where("clipped_at < ?", end_datetime) 
    else
      @clippings = Clipping.all
    end
    # render clippings as xml
    render :xml => @clippings.to_xml
  end

  def update_html_settings
    Settings.single_clipping_html_template = params[:template]
    Settings.book_title_html_template = params[:title_template]
    flash[:success] = "HTML clipping template updated."
    redirect_to export_path
  end
end

app/helpers/exports_helper.rb
module ExportsHelper
end

app/views/exports/show.html.haml
= content_for :title_element do
  Export : 

= content_for :title do 
  Export clippings

%p= link_to "Export all clippings", download_export_path

%h2 Export clippings by date range

= form_tag "/export/download", :method => :get do
  .clearfix
    %label Start Date
    .input
      = date_select("start_date", nil)

  .clearfix
    %label End Date
    .input
      = date_select("end_date", nil)

  .actions
    = submit_tag "Export", :class => "btn primary"

%h2 HTML template for clipping export

= form_tag "/export/update_html_settings" do
  .clearfix
    %label Single clipping format
    .input
      = text_area_tag "template", @html_template, :class => "xxlarge", :rows => 5
      %span.help-block
        Substitution variables:
        %code $quote
        %code $locations
        %code $note
        %br
        You can wrap conditional content for notes in 
        %code $ifnote
        and
        %code $endifnote
  .clearfix
    %label Book title/author format
    .input
      = text_area_tag "title_template", @title_template, :class => "xxlarge"
      %span.help-block
        Substitution variables
        %code $title
        %code $author

        
  .actions
    = submit_tag "Update", :class => "btn primary"