config/routes.rb
Clippr::Application.routes.draw do
  resources :authors do
    resources :books do
      member do
        get 'html_export'
      end
      resources :clippings do
        member do
          get 'html_export'
        end
        resource :instapaper_reference
      end
    end
  end
  resources :imports
  resources :clippings

  resource :export do
    member do
      get "download"
      post "update_html_settings"
    end
  end
  
  root :to => "books#index"
  
  

end

app/views/layouts/_modal_file_dialog.html.haml
#modal-file-dialog.modal.hide
  .modal-header
    = link_to raw("&times;"), "#", :class => "close"
    %h3 Import from file
    = form_tag imports_path, :multipart => true do
      .modal-body
        = file_field :import, :import_file
      .modal-footer
        -#= submit_tag "Upload file"
        = link_to "Upload file", "#", :class => "btn primary submit-file-upload"

app/views/layouts/_topbar.html.haml
.topbar
  .topbar-inner
    .container
      %h3= link_to "Clippr", "/"
      %ul.nav
        %li= link_to "Books", "/"
        %li= link_to "Authors", authors_path
        %li= link_to "Clippings", clippings_path
        %li= link_to "Export", export_path
      -#.import=link_to "Import"
      %ul.nav.secondary-nav
        %li.dropdown{"data-dropdown" => "dropdown"}
          = link_to "Import", "#", :class => "dropdown-toggle"
          %ul.dropdown-menu
            %li
              = form_tag(imports_path, :class => "invisible") do
                &nbsp;
                
              = link_to "Import from Kindle", imports_path, :class => "import-from-kindle"
            %li= link_to "Import from file", "#", :class => "import-from-file", "data-controls-modal" => "modal-file-dialog"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = yield :title_element
      Clippr
    = stylesheet_link_tag "application"
    = javascript_include_tag "application" 
    = csrf_meta_tag
  %body
    = render "layouts/topbar"
    .container.main
      #flash
        - flash.each do |key, value|
          %div{:class => "alert-message #{key}"}= value
      %h1= yield :title
      = yield
      = render "layouts/modal_file_dialog"
      = cleardiv